name: Oasys Blockscout Publish Docker image

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: self-hosted
    env:
      RELEASE_VERSION: 6.9.2
      DOCKER_CHAIN_NAME: oasys
      SHORT_SHA: xae1234
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Add host to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ec2-54-178-33-215.ap-northeast-1.compute.amazonaws.com >> ~/.ssh/known_hosts

      - name: Set up SSH agent
        run: |
          eval "$(ssh-agent -s)"
          echo "${{ secrets.ARM_RUNNER_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-add ~/.ssh/id_rsa

      - name: Debug SSH Connection
        run: ssh -o StrictHostKeyChecking=no ec2-user@ec2-54-178-33-215.ap-northeast-1.compute.amazonaws.com "echo 'SSH connection successful'"

      - name: Setup repo
        uses: ./.github/actions/setup-repo
        id: setup
        with:
          docker-username: ${{ secrets.DOCKER_USERNAME }}
          docker-password: ${{ secrets.DOCKER_PASSWORD }}
          docker-remote-multi-platform: true

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./docker/Dockerfile
          push: true
          tags: blockscout/blockscout-${{ env.DOCKER_CHAIN_NAME }}:${{ env.RELEASE_VERSION }}-postrelease-${{ env.SHORT_SHA }}
          labels: https://github.com/bibi4c/blockscout-v6
          platforms: |
            linux/amd64
            linux/arm64/v8
          build-args: |
            CACHE_EXCHANGE_RATES_PERIOD=
            API_V1_READ_METHODS_DISABLED=false
            DISABLE_WEBAPP=false
            API_V1_WRITE_METHODS_DISABLED=false
            CACHE_TOTAL_GAS_USAGE_COUNTER_ENABLED=
            ADMIN_PANEL_ENABLED=false
            CACHE_ADDRESS_WITH_BALANCES_UPDATE_INTERVAL=
            BLOCKSCOUT_VERSION=v${{ env.RELEASE_VERSION }}-beta.+commit.${{ env.SHORT_SHA }}
            RELEASE_VERSION=${{ env.RELEASE_VERSION }}
